### ISSUE TITLE
Allow users to (O-)authorize client applications on the fly via a browser window

### ISSUE THREAD

**Issue by kupietz** [KorAP/RKorAPClient#4]
The current procedure requires users to generate an access token themselves and in advance in their KorAP OAuth-settings, to copy the token and to store it in their keyring using `RKorAPClient::persistAccessToken(kco, accessToken="<token>")` or to pass it with each `new("KorAPConnection", accesToken = "<token>")`.

It would be nice if also client applications could initiate the authorization process, using [`httr::oauth_endpoint()`](https://httr.r-lib.org/reference/oauth_endpoint.html), [`httr::oauth_app()`](https://httr.r-lib.org/reference/oauth_app.html), so that with [`httr::oauth2.0_token()`](https://httr.r-lib.org/reference/oauth2.0_token.html)  the client application can open a browser window where the user is asked to grant KorAP-access to it and which, in the case of success, sends the access token to the client package callback function, listening by default on `http://localhost:1410` (as described, e.g. in this [R-hub blog post](https://blog.r-hub.io/2021/01/25/oauth-2.0/)). 

I think this is the standard procedure now (exemplified in the [httr package](https://httr.r-lib.org/index.html) for Google, GitHub, Facebook, Vimeo, ...) and we do already have most if not all the functionality provided by Kustvakt, maybe lacking not much more than a page in Kalamar that asks the user to grant the access.

To get an idea, how this should look like, you can try the googldrive package that provides a built-in fallback OAuth app:

```R
library("googledrive")
drive_find(n_max = 30)
```
After logging in this open the following access request:
![Bildschirmfoto von 2021-09-07 16-25-49](https://user-images.githubusercontent.com/11092081/132363554-3be929de-0ae7-4998-8758-acb5c7a6ddf9.png)

We can discuss if we also want have such a built-in fallback app. See the discussion on the security risk [here](https://gargle.r-lib.org/articles/get-api-credentials.html#oauth-client-id-and-secret).

**Comment by kupietz** [comment]
See also https://github.com/KorAP/Kalamar/issues/54

**Comment by notesjor** [comment]
Die Authentifizierung via OAuth2 ist zweifelslos ein wichtiges Feature. Aber man sollte auch bedenken welche Apps die API nutzen. Wenn eine APP oder sogar eine Plattform wie OWID Anfragen und Funktionen von KorAP im großen Umfang nutzt, dann lohnt sich die Umsetzung von OAuth2. 
Wenn man aber als Solo-Dev mal eben schnell eine Abfrage zusammen hacken will, dann ist der Prozess recht kompliziert. Auch weil ich das schon an anderer Stelle angemerkt habe: Wäre es nicht sinnvoll einen parallelen Auth-Flow zu haben, der mit einem einfachen JWT auskommt? - Der JWT sollte mEn mit einem Private Key signiert werden - dass macht den Prozess sicher. Von einer symetrischen Lösung ist abzuraten. In das JWT müssten dann halt alles scopes und der Nutzername hinterlegt werden. Das Szenario wäre dann nur für Solo-Devs, kleine Apps/Skripte - größere Live-Anwendungen könnten dann leicht auf OAuth2 migrieren.
